# See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/


[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "checkn"
description = "Check if a name is already defined somewhere"
authors = [
    {name="Richard LeBer", email = "richard.leber@gmail.com"}
]
license = "MIT"
license-files = ["LICENSE.md"]
readme = "README.md"
requires-python = ">=3.12"
dynamic = ["version", "dependencies"]

[project.scripts] 
checkn = "checkn:entry"

# [project.urls] # TODO Complete or remove
# Homepage = "url"
# Documentation = "url"
# Repository = "url"
# Etc. See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#urls

[tool.setuptools.dynamic]
version = {attr = "checkn.__version__"}
dependencies = {file = ["requirements.txt"]}